"""Rebuild the frozen retail catalogue from the checked-in wowdata snapshots."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "docs/architecture"
encounters = json.loads((DATA / "2026-09-10-journal-encounters.json").read_text(encoding="utf-8-sig"))["data"]["rows"]
instances = json.loads((DATA / "2026-09-10-journal-instances.json").read_text(encoding="utf-8-sig"))["data"]["rows"]
by_id = {row["ID"]: row for row in instances if row.get("Name_lang")}
valid = [row for row in encounters if row.get("Name_lang") and row["JournalInstanceID"] in by_id]
assert len({row["ID"] for row in valid}) == len(valid)
assert 800 < len(valid) <= 4096
used = {row["JournalInstanceID"] for row in valid}
quote = lambda text: json.dumps(text, ensure_ascii=False)
lines = ["-- Generated by tests/build_journal_catalog.py; do not edit individual rows.",
         "-- wowdata: retail wow/cn/zhCN, build 12.1.0.69587; JournalInstance + JournalEncounter.",
         "local I = _G.LycheeInternal", "I.Builtin.JournalCatalog = {", '    build="12.1.0.69587",', "    instances={"]
for instance_id in sorted(used):
    row = by_id[instance_id]
    icon = row["ButtonSmallFileDataID"] or row["ButtonFileDataID"]
    lines.append(f'        [{instance_id}]={{{quote(row["Name_lang"])}, {icon if icon > 0 else "nil"}}},')
lines.extend(["    },", "    encounters={"])
for row in sorted(valid, key=lambda row: (row["JournalInstanceID"], row["OrderIndex"], row["ID"])):
    lines.append(f'        {{{row["ID"]}, {row["JournalInstanceID"]}, {quote(row["Name_lang"])}}},')
lines.extend(["    },", "}", ""])
(ROOT / "package/Lychee/Builtin/Data/JournalCatalog.lua").write_text("\n".join(lines), encoding="utf-8", newline="\n")
print(f"Journal catalogue: {len(valid)} encounters, {len(used)} instances; {len(encounters)-len(valid)} rows without an available named instance omitted.")
