local I=_G.LycheeInternal
-- Keys are Blizzard setting variables, not translated labels. Native labels
-- and variable names are always searchable; these add familiar short names.
I.Builtin.SettingsAliases={
 autoLootDefault={"自动拾取","自動拾取","自动捡东西","自动拾取物品","auto loot","autoloot"},
 autoLootRate={"拾取速度","loot speed"},
 autoSelfCast={"自动自我施法","自动对自己施法","auto self cast"},
 autoInteract={"自动互动","自动交互","auto interact"},
 autoDismountFlying={"自动取消飞行坐骑","自动下飞行坐骑","auto dismount flying"},
 autoDismount={"自动下马","自动取消坐骑","auto dismount"},
 autoStand={"自动站立","auto stand"},
 autoClearAFK={"自动取消暂离","auto clear afk"},
 interactOnLeftClick={"左键互动","左键交互","left click interact"},
 cameraDistanceMaxZoomFactor={"最大镜头距离","最远镜头","镜头距离","camera distance","max camera distance","camera zoom"},
 cameraYawMoveSpeed={"镜头水平速度","camera yaw speed"},
 cameraPitchMoveSpeed={"镜头垂直速度","camera pitch speed"},
 cameraSmoothStyle={"镜头跟随","镜头跟随模式","camera following","camera follow style"},
 cameraShake={"镜头震动","屏幕震动","camera shake"},
 mouseSpeed={"鼠标速度","鼠标灵敏度","mouse speed","mouse sensitivity"},
 mouseInvertPitch={"反转鼠标","鼠标反转","invert mouse"},
 enableMouseSpeed={"启用鼠标灵敏度","use mouse sensitivity"},
 ActionButtonUseKeyDown={"按下施法","按下按键施法","cast on key down"},
 SpellQueueWindow={"法术队列窗口","技能队列窗口","spell queue window"},
 enableFloatingCombatText={"浮动战斗文字","floating combat text"},
 floatingCombatTextCombatDamage={"伤害数字","伤害浮字","damage text"},
 floatingCombatTextCombatHealing={"治疗数字","治疗浮字","healing text"},
 nameplateShowEnemies={"敌方姓名板","敌人姓名板","敌对姓名板","enemy nameplates"},
 nameplateShowFriends={"友方姓名板","队友姓名板","friendly nameplates"},
 nameplateMotion={"姓名板排列","姓名板堆叠","nameplate motion","nameplate stacking"},
 nameplateShowAll={"总是显示姓名板","始终显示姓名板","always show nameplates"},
 nameplateMaxDistance={"姓名板距离","姓名板最大距离","nameplate distance"},
 UnitNameOwn={"自己的名字","显示自身名字","own name"},
 UnitNameNPC={"npc名字","NPC名称","npc names"},
 UnitNameFriendlyPlayerName={"友方玩家名字","friendly player names"},
 UnitNameEnemyPlayerName={"敌方玩家名字","enemy player names"},
 showTargetOfTarget={"目标的目标","目标目标","target of target","tot"},
 statusText={"状态文字","血量数字","status text"},
 statusTextDisplay={"状态文字格式","血量显示格式","status text display"},
 showTimestamps={"聊天时间戳","聊天时间","chat timestamps"},
 chatStyle={"聊天风格","聊天样式","chat style"},
 chatBubbles={"聊天气泡","对话气泡","chat bubbles"},
 chatBubblesParty={"小队聊天气泡","party chat bubbles"},
 profanityFilter={"语言过滤","脏话过滤","敏感词过滤","profanity filter"},
 guildMemberNotify={"公会上线通知","公会成员通知","guild member alerts"},
 blockTrades={"屏蔽交易","阻止交易","拒绝交易","block trades"},
 blockChannelInvites={"屏蔽频道邀请","阻止频道邀请","block channel invites"},
 colorblindMode={"色盲模式","色盲","colorblind mode","colour blind mode"},
 colorblindSimulator={"色盲滤镜","色盲类型","colorblind filter"},
 colorblindWeaknessFactor={"色盲滤镜强度","colorblind intensity"},
 reducedMotion={"减少动态效果","减少动画","reduced motion"},
 floatingCombatTextFloatMode={"战斗文字滚动","combat text scroll"},
 Sound_EnableAllSound={"全部声音","游戏声音","游戏音频","总声音开关","all sound","game sound","sound"},
 Sound_EnableMusic={"音乐开关","背景音乐","音乐","音樂","music"},
 Sound_EnableSFX={"音效开关","游戏音效","音效","sound effects","sfx"},
 Sound_EnableAmbience={"环境声音开关","环境音","環境音","ambience","ambient sound"},
 Sound_EnableDialog={"对话声音开关","人物对白","对话","對話","dialogue","dialog"},
 Sound_EnableSoundWhenGameIsInBG={"后台声音","后台播放声音","切出去有声音","sound in background","background sound"},
 Sound_EnableReverb={"混响","声音混响","reverb"},
 Sound_EnableDSPEffects={"音频效果","dsp effects"},
 Sound_OutputDriverIndex={"声音输出设备","音频输出设备","扬声器","耳机","sound output device","speakers","headphones"},
 Sound_NumChannels={"声道数","声音通道数","sound channels"},
 Sound_MaxCacheSizeInBytes={"音频缓存","声音缓存","sound cache"},
 Sound_EnablePetSounds={"宠物声音","pet sounds"},
 Sound_EnableErrorSpeech={"错误语音","技能错误语音","error speech"},
 Sound_EnableEmoteSounds={"表情声音","emote sounds"},
 Sound_EnableMountSounds={"坐骑声音","mount sounds"},
 PROXY_VOICE_INPUT_VOLUME={"麦克风音量","麦克风增益","话筒音量","输入音量","麥克風音量","microphone volume","mic volume","input volume"},
 PROXY_VOICE_OUTPUT_VOLUME={"语音聊天音量","语音音量","队友语音音量","語音音量","voice volume","voice chat volume","voice output volume"},
 PROXY_VOICE_INPUT_DEVICE={"麦克风设备","语音输入设备","microphone device","voice input device"},
 PROXY_VOICE_OUTPUT_DEVICE={"语音输出设备","voice output device"},
 PROXY_VOICE_DUCKING={"语音压低音量","语音时降低游戏音量","voice ducking"},
 PROXY_VOICE_SENSITIVITY={"语音灵敏度","麦克风灵敏度","voice sensitivity"},
 PROXY_VOICE_CHAT_MODE={"语音模式","按键说话","voice chat mode","push to talk"},
 PROXY_USE_UI_SCALE={"界面缩放开关","使用界面缩放","use ui scale"},
 PROXY_UI_SCALE={"界面缩放","ui缩放","界面大小","UI比例","介面縮放","ui scale","interface scale","interface size"},
 uiScale={"界面缩放","ui缩放","界面大小","ui scale"},
 useUiScale={"界面缩放开关","使用界面缩放","use ui scale"},
 maxFPS={"前台帧数","前台帧率","最大帧数","帧数上限","fps上限","foreground fps","max fps","frame rate limit"},
 maxFPSBk={"后台帧数","后台帧率","后台最大帧数","background fps","background frame rate"},
 targetFPS={"目标帧率","目标帧数","target fps"},
 gxVSync={"垂直同步","垂直同步开关","vsync","v sync","vertical sync"},
 gxWindow={"窗口模式","windowed mode"},
 gxMaximize={"窗口最大化","maximize window"},
 gxResolution={"分辨率","屏幕分辨率","resolution","screen resolution"},
 gxRefresh={"刷新率","屏幕刷新率","refresh rate"},
 gxApi={"图形接口","图形api","显卡接口","graphics api","directx"},
 gxAdapter={"显卡","图形处理器","graphics card","gpu"},
 graphicsQuality={"画质","画面质量","图形质量","graphics quality","graphics preset"},
 graphicsShadowQuality={"阴影质量","阴影效果","shadow quality","shadows"},
 graphicsLiquidDetail={"液体细节","水面效果","liquid detail","water quality"},
 graphicsParticleDensity={"粒子密度","粒子效果","particle density"},
 graphicsSSAO={"环境光遮蔽","环境遮蔽","ssao","ambient occlusion"},
 graphicsDepthEffects={"景深效果","depth effects"},
 graphicsComputeEffects={"计算效果","compute effects"},
 graphicsViewDistance={"视野距离","视距","view distance"},
 graphicsEnvironmentDetail={"环境细节","environment detail"},
 graphicsGroundClutter={"地表景观","地面杂物","ground clutter"},
 graphicsTextureResolution={"材质分辨率","纹理质量","texture resolution","texture quality"},
 graphicsSpellDensity={"法术密度","技能特效密度","spell density"},
 graphicsProjectedTextures={"投射材质","投影纹理","projected textures"},
 Gamma={"伽马","画面亮度","gamma","brightness"},
 contrast={"对比度","contrast"},
 brightness={"亮度","brightness"},
}
local aliases=I.Builtin.SettingsAliases
local proxies={PROXY_FOREGROUND_FPS="maxFPS",PROXY_BACKGROUND_FPS="maxFPSBk",PROXY_TARGET_FPS="targetFPS",
 PROXY_VERTICAL_SYNC="gxVSync",PROXY_RESOLUTION="gxResolution",PROXY_GRAPHICS_API="gxApi",PROXY_GX_ADAPTER="gxAdapter",
 PROXY_STATUS_TEXT="statusTextDisplay",PROXY_NPC_NAMES="UnitNameNPC",PROXY_MOUSE_LOOK_SPEED="mouseSpeed",
 PROXY_SELF_CAST="autoSelfCast",UNIT_NAMEPLATES_ENABLE_STACKING="nameplateMotion",nameplateShowFriendlyPlayers="nameplateShowFriends",
 Contrast="contrast",Brightness="brightness"}
for proxy,original in pairs(proxies) do aliases[proxy]=aliases[original] end
aliases.PROXY_DISPLAY_MODE={"显示模式","窗口模式","全屏模式","display mode","window mode","screen mode"}
aliases.PROXY_PRIMARY_MONITOR={"显示器","屏幕选择","monitor","display monitor"}
aliases.PROXY_RESOLUTION_RENDER_SCALE={"渲染倍数","渲染缩放","渲染比例","render scale","resolution scale"}
aliases.PROXY_CAMERA_FOV={"视野范围","镜头视野","视角范围","fov","field of view"}
aliases.PROXY_ANTIALIASING={"抗锯齿","抗鋸齒","anti aliasing","antialiasing","aa"}
aliases.PROXY_FXAA={"图像抗锯齿","fxaa","cmaa"}
aliases.PROXY_MSAA={"多重采样抗锯齿","msaa","multisampling"}
aliases.PROXY_TRIPLE_BUFFERING={"三倍缓冲","三重缓冲","triple buffering"}
aliases.LowLatencyMode={"低延迟模式","低延迟","low latency mode","nvidia reflex"}
aliases.PROXY_ENABLE_INTERACT={"交互按键","互动按键","interact key"}
aliases.enableMouseoverCast={"鼠标悬停施法","鼠标指向施法","mouseover cast","mouseover casting"}
aliases.ActionButtonUseKeyHeldSpell={"按住施法","按住连续施法","hold to cast","press and hold casting"}
aliases.lockActionBars={"锁定动作条","动作条锁定","lock action bars"}
aliases.countdownForCooldowns={"冷却数字","冷却倒计时","显示冷却时间","cooldown numbers","cooldown countdown"}
aliases.PROXY_ACTION_TARGETING={"动作瞄准","动作目标","action targeting"}
aliases.RAIDsettingsEnabled={"团队画质开关","使用团队画质","raid graphics enabled"}
for n=2,8 do aliases["PROXY_SHOW_ACTIONBAR_"..n]={"动作条"..n,"动作条 "..n,"action bar "..n,"actionbar "..n} end

-- Audio names remain searchable without command parsing or volume writes.
aliases.Sound_MasterVolume={"主音量","总音量","總音量","全局音量","游戏音量","音量","master volume","game volume","overall volume","sound volume","volume","audio"}
aliases.Sound_MusicVolume={"音乐音量","音樂音量","背景音乐音量","背景音樂音量","music volume","background music volume","bgm volume"}
aliases.Sound_SFXVolume={"音效音量","效果音量","sound effects volume","effects volume","sfx volume"}
aliases.Sound_AmbienceVolume={"环境音量","環境音量","环境声音","环境音","ambience volume","ambient volume","ambient sound volume"}
aliases.Sound_DialogVolume={"对话音量","對話音量","对白音量","人物语音","dialog volume","dialogue volume","character voice volume"}
