-- Generated by tools/build_client_tocs.py; edit tools/client_manifest.json.
local _,I=...
local chinese=GetLocale()=="zhCN" or GetLocale()=="zhTW"
local root="Interface\\AddOns\\Lychee\\Media\\MenuIcons\\"
I.Modules.Definitions={
    {id="lychee.exwind",module="Exwind",scope={products={"retail"}},requires={}},
    {id="lychee.ellesmere",module="Ellesmere",scope={products={"retail"}},requires={}},
}
I.Modules.Presentation={
    ["lychee.exwind"]={source={id="Lychee_Integrations",title=chinese and "插件集成" or "Addon integrations"},description=chinese and "用 EX：搜索设置页面或解锁界面" or "Use EX: to find settings pages or unlock the layout",icon=root.."settings.tga",order=1,prefixes={}},
    ["lychee.ellesmere"]={source={id="Lychee_Integrations",title=chinese and "插件集成" or "Addon integrations"},description=chinese and "用 EUI：搜索设置页面或解锁界面" or "Use EUI: to find settings pages or unlock the layout",icon=root.."settings.tga",order=2,prefixes={}},
}
