-- Generated by tools/build_client_tocs.py; edit tools/client_manifest.json.
local _,I=...
local chinese=GetLocale()=="zhCN" or GetLocale()=="zhTW"
local root="Interface\\AddOns\\Lychee\\Media\\MenuIcons\\"
I.Modules.Definitions={
    {id="lychee.addon-inspector",module="AddonInspector",scope={products={"retail","classic","titan","anniversary"}},requires={"GetMouseFoci"}},
}
I.Modules.Presentation={
    ["lychee.addon-inspector"]={source={id="Lychee_Inspector",title=chinese and "插件识别" or "Addon Inspector"},description=chinese and "指向界面，识别来源插件" or "Point at a frame to identify its addon",icon=root.."addon-inspector.tga",order=15,prefixes={}},
}
