-- Generated by tools/build_client_tocs.py; edit tools/client_manifest.json.
local _,I=...
local chinese=GetLocale()=="zhCN" or GetLocale()=="zhTW"
local root="Interface\\AddOns\\Lychee\\Media\\MenuIcons\\"
I.Modules.Definitions={
    {id="lychee.player-spells",module="PlayerSpells",scope={products={"retail","classic","titan","anniversary"}},requires={}},
    {id="lychee.mounts",module="Mounts",scope={products={"retail","classic","titan"}},requires={"C_MountJournal.GetMountIDs","C_MountJournal.GetMountInfoByID"}},
    {id="lychee.crests",module="Crests",scope={products={"retail"}},requires={}},
    {id="lychee.game-menus",module="GameMenus",scope={products={"retail","classic","titan","anniversary"}},requires={}},
    {id="lychee.great-vault",module="GreatVault",scope={products={"retail"}},requires={}},
    {id="lychee.bags",module="Bags",scope={products={"retail","classic","titan","anniversary"}},requires={"C_Container.GetContainerNumSlots","C_Container.GetContainerItemInfo"}},
    {id="lychee.talent-loadouts",module="TalentLoadouts",scope={products={"retail"}},requires={}},
    {id="lychee.equipment-sets",module="EquipmentSets",scope={products={"retail","classic","titan"}},requires={"C_EquipmentSet.GetEquipmentSetIDs","C_EquipmentSet.GetEquipmentSetInfo","C_EquipmentSet.UseEquipmentSet"}},
    {id="lychee.blizzard-settings",module="BlizzardSettings",scope={products={"retail","classic","titan","anniversary"}},requires={}},
    {id="lychee.keystones",module="Keystones",scope={products={"retail"}},requires={}},
    {id="lychee.achievements",module="Achievements",scope={products={"retail","classic","titan"}},requires={"GetCategoryList","GetAchievementInfo","GetAchievementCriteriaInfo","GetAchievementNumCriteria","GetAchievementLink"}},
}
I.Modules.Presentation={
    ["lychee.player-spells"]={source={id="Lychee_Player",title=chinese and "玩家功能" or "Player features"},description=chinese and "搜索并施放已学技能" or "Find and cast learned spells",icon=root.."spellbook.tga",order=3,prefixes={"技能","spell","spells","玩家技能"}},
    ["lychee.mounts"]={source={id="Lychee_Player",title=chinese and "玩家功能" or "Player features"},description=chinese and "搜索并召唤坐骑" or "Find and summon mounts",icon=root.."mounts.tga",order=4,prefixes={"坐骑","mounts"}},
    ["lychee.crests"]={source={id="Lychee_Player",title=chinese and "玩家功能" or "Player features"},description=chinese and "查看当前角色的纹章数量" or "View this character's crest balances",icon=root.."currency.tga",order=5,prefixes={"纹章"}},
    ["lychee.game-menus"]={source={id="Lychee_Player",title=chinese and "玩家功能" or "Player features"},description=chinese and "快速打开游戏面板" or "Quickly open game panels",icon=root.."game-menu.tga",order=6,prefixes={"菜单","游戏菜单"}},
    ["lychee.great-vault"]={source={id="Lychee_Player",title=chinese and "玩家功能" or "Player features"},description=chinese and "查看宏伟宝库进度与奖励" or "View Great Vault progress and rewards",icon=root.."great-vault.tga",order=8,prefixes={"宏伟宝库","宝库"}},
    ["lychee.bags"]={source={id="Lychee_Player",title=chinese and "玩家功能" or "Player features"},description=chinese and "搜索物品并定位背包" or "Search and locate bag items",icon=root.."toys.tga",order=9,prefixes={"背包","物品","bags","背包物品"}},
    ["lychee.talent-loadouts"]={source={id="Lychee_Player",title=chinese and "玩家功能" or "Player features"},description=chinese and "搜索并切换天赋方案" or "Find and switch talent loadouts",icon=root.."talents.tga",order=10,prefixes={"天赋","天赋方案","talents"}},
    ["lychee.equipment-sets"]={source={id="Lychee_Player",title=chinese and "玩家功能" or "Player features"},description=chinese and "搜索并切换装备方案" or "Find and switch equipment sets",icon=root.."character.tga",order=11,prefixes={"装备","装备方案","gear"}},
    ["lychee.blizzard-settings"]={source={id="Lychee_Player",title=chinese and "玩家功能" or "Player features"},description=chinese and "定位设置、重载界面与冷却管理器" or "Find settings, reload, and manage cooldowns",icon=root.."settings.tga",order=12,prefixes={"设置","暴雪设置","settings"}},
    ["lychee.keystones"]={source={id="Lychee_Player",title=chinese and "玩家功能" or "Player features"},description=chinese and "队伍钥匙、分数与副本传送" or "Party keys, ratings, and dungeon teleports",icon=root.."keystone.tga",order=13,prefixes={"钥匙","key","keys","队伍钥匙"}},
    ["lychee.achievements"]={source={id="Lychee_Player",title=chinese and "玩家功能" or "Player features"},description=chinese and "搜索成就、查看进度与分享链接" or "Find achievements, progress, and share links",icon=root.."achievements.tga",order=14,prefixes={"成就","achievement","achievements"}},
}
