-- Generated by tools/build_client_tocs.py; edit tools/client_manifest.json.
local I = _G.LycheeInternal
I.ProviderModules = I.ProviderModules or {}
I.ProviderModules.Definitions = {
    {id="builtin.exwind",module="Exwind",scope={products={"retail"}},requires={}},
    {id="builtin.ellesmere",module="Ellesmere",scope={products={"retail"}},requires={}},
    {id="builtin.player-spells",module="PlayerSpells",scope={products={"retail","classic","titan","anniversary"}},requires={}},
    {id="builtin.mounts",module="Mounts",scope={products={"retail","classic","titan"}},requires={"C_MountJournal.GetMountIDs","C_MountJournal.GetMountInfoByID"}},
    {id="builtin.crests",module="Crests",scope={products={"retail"}},requires={}},
    {id="builtin.game-menus",module="GameMenus",scope={products={"retail","classic","titan","anniversary"}},requires={}},
    {id="builtin.bosses",module="Bosses",scope={products={"retail"}},requires={}},
    {id="builtin.great-vault",module="GreatVault",scope={products={"retail"}},requires={}},
    {id="builtin.bags",module="Bags",scope={products={"retail","classic","titan","anniversary"}},requires={"C_Container.GetContainerNumSlots","C_Container.GetContainerItemInfo"}},
    {id="builtin.talent-loadouts",module="TalentLoadouts",scope={products={"retail"}},requires={}},
    {id="builtin.equipment-sets",module="EquipmentSets",scope={products={"retail","classic","titan"}},requires={"C_EquipmentSet.GetEquipmentSetIDs","C_EquipmentSet.GetEquipmentSetInfo","C_EquipmentSet.UseEquipmentSet"}},
    {id="builtin.blizzard-settings",module="BlizzardSettings",scope={products={"retail","classic","titan","anniversary"}},requires={}},
    {id="builtin.keystones",module="Keystones",scope={products={"retail"}},requires={}},
    {id="builtin.achievements",module="Achievements",scope={products={"retail","classic","titan"}},requires={"GetCategoryList","GetAchievementInfo","GetAchievementCriteriaInfo","GetAchievementNumCriteria","GetAchievementLink"}},
    {id="builtin.addon-inspector",module="AddonInspector",scope={products={"retail","classic","titan","anniversary"}},requires={"GetMouseFoci"}},
    {id="builtin.ldt",module="LDT",scope={products={"retail"}},requires={"C_Spell.GetSpellName"}},
}
