-- Generated by tools/build_client_tocs.py; edit tools/client_manifest.json.
local _,I=...
local chinese=GetLocale()=="zhCN" or GetLocale()=="zhTW"
local root="Interface\\AddOns\\Lychee\\Media\\MenuIcons\\"
I.Modules.Definitions={
    {id="lychee.bosses",module="Bosses",scope={products={"retail"}},requires={}},
    {id="lychee.ldt",module="LDT",scope={products={"retail"}},requires={"C_Spell.GetSpellName"}},
}
I.Modules.Presentation={
    ["lychee.bosses"]={source={id="Lychee_Encounters",title=chinese and "副本资料" or "Encounter reference"},description=chinese and "搜索团本首领和技能并查看指南" or "Find raid bosses and abilities in the journal",icon=root.."skull.tga",order=7,prefixes={"团本首领","首领","bosses"}},
    ["lychee.ldt"]={source={id="Lychee_Encounters",title=chinese and "副本资料" or "Encounter reference"},description=chinese and "搜索地下城怪物和技能并查看资料" or "Search dungeon enemies and abilities, and view their details",icon=root.."skull.tga",order=16,prefixes={}},
}
