-- Generated by tools/build_client_tocs.py; edit tools/client_manifest.json.
_G.LycheeInternal = _G.LycheeInternal or {}
local I = _G.LycheeInternal
I.ClientProfiles = {
    ["retail"]={minInterface=100000,maxInterface=199999},
    ["classic"]={minInterface=50500,maxInterface=50599},
    ["titan"]={minInterface=38000,maxInterface=38099},
    ["anniversary"]={minInterface=20505,maxInterface=20599},
    ["forever"]={minInterface=16001,maxInterface=16099},
}
