"""Generate client TOCs from one ordered manifest; --check detects drift."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ADDON = ROOT / "package/Lychee"


def validate(manifest):
    products = set(manifest['clients'])
    ids, modules, owned = set(), set(), set()
    for spec in manifest['providers']:
        if set(spec) != {'id', 'module', 'products', 'files', 'requires', 'locales'}:
            raise ValueError('Unknown or missing Provider declaration fields')
        if spec['id'] in ids or spec['module'] in modules:
            raise ValueError('Duplicate Provider identity')
        ids.add(spec['id']); modules.add(spec['module'])
        if not spec['products'] or len(set(spec['products'])) != len(spec['products']) or not set(spec['products']) <= products:
            raise ValueError('Invalid Provider products: ' + spec['id'])
        for path in [spec['locales'], *spec['files']]:
            if Path(path).is_absolute() or '..' in Path(path).parts or '\\' in path:
                raise ValueError('Unsafe Provider path: ' + path)
            if path in owned:
                raise ValueError('File owned by multiple Providers: ' + path)
            owned.add(path)
        for symbol in spec.get('requires', []):
            if not re.fullmatch(r'[A-Za-z_][A-Za-z_0-9]*(\.[A-Za-z_][A-Za-z_0-9]*)*', symbol):
                raise ValueError('Invalid capability: ' + symbol)
    references = [item['provider'] for item in manifest['files'] if 'provider' in item]
    if len(references) != len(ids) or set(references) != ids:
        raise ValueError('Every Provider needs exactly one load position')
    for item in manifest['files']:
        if item.get('providerLocales'):
            if item != {'providerLocales': True}:
                raise ValueError('Invalid locale load position')
            continue
        if 'path' in item and set(item) != {'path', 'products'}:
            raise ValueError('Unknown shared file fields')
        if 'provider' in item and set(item) != {'provider'}:
            raise ValueError('Provider load positions must not repeat products/files')
        if 'path' in item and item['path'] in owned:
            raise ValueError('Provider file repeated as shared: ' + item['path'])
        if 'path' in item and (not item['products'] or not set(item['products']) <= products):
            raise ValueError('Invalid shared products')
    if sum(item.get('providerLocales', False) for item in manifest['files']) != 1:
        raise ValueError('Provider locales need exactly one load position')


def runtime_definitions(manifest):
    lines = ['-- Generated by tools/build_client_tocs.py; edit tools/client_manifest.json.',
             'local I = _G.LycheeInternal', 'I.Builtin = I.Builtin or {}',
             'I.Builtin.Definitions = {']
    def strings(values):
        return '{' + ','.join(json.dumps(value) for value in values) + '}'
    for spec in manifest['providers']:
        lines.append('    {id=%s,module=%s,scope={products=%s},requires=%s},' % (
            json.dumps(spec['id']), json.dumps(spec['module']), strings(spec['products']), strings(spec.get('requires', []))))
    lines.append('}')
    return '\n'.join(lines) + '\n'


def file_list(manifest, product):
    providers = {spec['id']: spec for spec in manifest['providers']}
    paths = []
    for item in manifest['files']:
        if item.get('providerLocales'):
            paths.extend(spec['locales'] for spec in manifest['providers'] if product in spec['products'])
            continue
        spec = providers[item['provider']] if 'provider' in item else item
        if product in spec['products']:
            paths.extend(spec['files'] if 'provider' in item else [spec['path']])
    if len(set(paths)) != len(paths):
        raise ValueError('Duplicate loaded file: ' + product)
    return paths


def render(manifest, product):
    client = manifest["clients"][product]
    lines = [
        f'## Interface: {client["interface"]}',
        '## Title: |cffd53c49Lychee|r Launcher',
        '## Title-zhCN: |cffd53c49荔枝|r启动器',
        '## Title-zhTW: |cffd53c49荔枝|r启动器',
        '## Notes: Universal launcher for World of Warcraft',
        '## Notes-zhCN: 魔兽世界万用启动器',
        '## Notes-zhTW: 魔兽世界万用启动器',
        '## Author: Lychee',
        f'## Version: {manifest["version"]}',
        '## SavedVariables: LycheeDB',
        '## Bindings: Bindings.xml',
        '',
    ]
    for path in file_list(manifest, product):
        if not (ADDON / path).is_file():
            raise SystemExit(f'Missing file: {path}')
        lines.append(path)
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    manifest = json.loads((ROOT / 'tools/client_manifest.json').read_text())
    validate(manifest)
    definitions = ADDON / 'Builtin/Definitions.lua'
    generated = runtime_definitions(manifest)
    if args.check:
        if not definitions.is_file() or definitions.read_text(encoding='utf-8') != generated:
            raise SystemExit('Builtin definitions drift')
    else:
        definitions.write_text(generated, encoding='utf-8')
    for product, client in manifest['clients'].items():
        text = render(manifest, product)
        names = [f'Lychee_{client["suffix"]}.toc']
        if product == 'retail':
            names.append('Lychee.toc')
        for name in names:
            target = ADDON / name
            if args.check:
                if not target.is_file() or target.read_text(encoding='utf-8') != text:
                    raise SystemExit(f'TOC drift: {name}')
            else:
                target.write_text(text, encoding='utf-8')
        fixture = ROOT / 'lychee-sdk/examples/ThirdPartyFixture'
        template = (fixture / 'ThirdPartyFixture.toc').read_text(encoding='utf-8')
        example = re.sub(r'^## Interface:.*$', f'## Interface: {client["interface"]}', template, flags=re.M)
        target = fixture / f'ThirdPartyFixture_{client["suffix"]}.toc'
        if args.check:
            if not target.is_file() or target.read_text(encoding='utf-8') != example:
                raise SystemExit(f'Example TOC drift: {target.name}')
        else:
            target.write_text(example, encoding='utf-8')
    print('Client TOCs PASS: retail, classic, titan, anniversary + retail fallback')


if __name__ == '__main__':
    main()
