"""Generate the bounded Retail toy ID catalogue from a pinned wowdata export."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.loads((ROOT / "assets/toys/catalog.json").read_text())
    ids = data["itemIDs"]
    assert data["product"] == "wow" and data["table"] == "Toy"
    assert 0 < len(ids) <= data["sourceRowCount"] <= 4096
    assert ids == sorted(set(ids)) and all(type(i) is int and i > 0 for i in ids)
    lines = [f'-- Generated by tools/build_toy_catalog.py; wow {data["build"]} Toy.db2.',
             'local I = _G.LycheeInternal', 'I.ProviderModules.ToyIDs = {']
    for offset in range(0, len(ids), 16):
        lines.append('    ' + ','.join(map(str, ids[offset:offset + 16])) + ',')
    text = '\n'.join(lines + ['}', ''])
    output = ROOT / 'addon/Lychee/Providers/Toys/Data.lua'
    if args.check:
        assert output.read_text(encoding='utf-8') == text, 'Toy catalogue drift'
    else:
        output.write_text(text, encoding='utf-8')
    print(f'Toy catalogue PASS: {len(ids)} IDs, wow {data["build"]}')


if __name__ == '__main__':
    main()
