"""Rebuild the frozen retail catalogue from the checked-in wowdata snapshots."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "docs/architecture"
encounters = json.loads((DATA / "2026-09-10-journal-encounters.json").read_text(encoding="utf-8-sig"))["data"]["rows"]
instances = json.loads((DATA / "2026-09-10-journal-instances.json").read_text(encoding="utf-8-sig"))["data"]["rows"]
by_id = {row["ID"]: row for row in instances if row.get("Name_lang")}
valid = [row for row in encounters if row.get("Name_lang") and row["JournalInstanceID"] in by_id]
assert len({row["ID"] for row in valid}) == len(valid)
assert 800 < len(valid) <= 4096
used = {row["JournalInstanceID"] for row in valid}
quote = lambda text: json.dumps(text, ensure_ascii=False)
lines = ["-- Generated by tools/build_journal_catalog.py; do not edit individual rows.",
         "-- wowdata: retail wow/cn/zhCN, build 12.1.0.69587; JournalInstance + JournalEncounter.",
         "local I = _G.LycheeInternal", "I.Builtin.JournalCatalog = {", '    build="12.1.0.69587",', "    instances={"]
for instance_id in sorted(used):
    row = by_id[instance_id]
    icon = row["ButtonSmallFileDataID"] or row["ButtonFileDataID"]
    lines.append(f'        [{instance_id}]={{{quote(row["Name_lang"])}, {icon if icon > 0 else "nil"}}},')
lines.extend(["    },", f"    encounterCount={len(valid)},", "    -- Flat triples: encounter ID, instance ID, canonical name. No per-row tables.", "    encounters={"])
for row in sorted(valid, key=lambda row: (row["JournalInstanceID"], row["OrderIndex"], row["ID"])):
    lines.append(f'        {row["ID"]}, {row["JournalInstanceID"]}, {quote(row["Name_lang"])},')
lines.extend(["    },", "}", ""])
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
output = ROOT / "package/Lychee/Builtin/Bosses/JournalCatalog.lua"
rendered = "\n".join(lines)
if parser.parse_args().check:
    if output.read_text(encoding="utf-8") != rendered:
        raise SystemExit("Journal catalogue generation drift")
else:
    output.write_text(rendered, encoding="utf-8", newline="\n")
print(f"Journal catalogue: {len(valid)} encounters, {len(used)} instances; {len(encounters)-len(valid)} rows without an available named instance omitted.")
