"""Generate/check SDK declarations from one build-time contract. Never package/publish."""
from __future__ import annotations

import argparse
import json
from pathlib import Path, PurePosixPath
import re
import sys

DEFAULT_ROOT = Path(__file__).resolve().parents[1]


def contract_at(root: Path) -> dict:
    contract = json.loads((root / "tools/sdk_contract.json").read_text(encoding="utf-8"))
    if contract.get("schemaVersion") != 1:
        raise ValueError("unsupported SDK contract schema")
    for field in ("apiVersion", "apiRevision", "helperMinimumRevision"):
        if type(contract.get(field)) is not int or contract[field] < 1:
            raise ValueError(f"invalid {field}")
    if contract["helperMinimumRevision"] > contract["apiRevision"]:
        raise ValueError("helper compatibility floor exceeds current revision")
    contents = contract.get("contents")
    if not isinstance(contents, list) or not contents or any(not isinstance(p, str) for p in contents):
        raise ValueError("contents must be a nonempty list of relative SDK paths")
    if len(set(contents)) != len(contents):
        raise ValueError("duplicate SDK delivery file")
    for name in contents:
        path = PurePosixPath(name)
        if path.is_absolute() or ".." in path.parts or "\\" in name or ":" in name or str(path) != name:
            raise ValueError(f"invalid SDK delivery path: {name}")
        if name == "manifest.yaml":
            raise ValueError("manifest.yaml is included implicitly, not in its own contents")
    codes = contract.get("errorCodes")
    if (not isinstance(codes, list) or not codes or len(set(codes)) != len(codes)
            or any(not isinstance(code, str) or not re.fullmatch(r"[A-Z][A-Z_]+", code) for code in codes)):
        raise ValueError("invalid SDK error code list")
    return contract


def replace_one(text: str, pattern: str, value: str, path: str) -> str:
    text, count = re.subn(pattern, lambda _: value, text, flags=re.MULTILINE | re.DOTALL)
    if count != 1:
        raise ValueError(f"{path}: expected exactly one generated declaration, found {count}")
    return text


def expected_files(root: Path, contract: dict) -> dict[str, str]:
    version, revision, floor = (contract[k] for k in ("apiVersion", "apiRevision", "helperMinimumRevision"))
    host_path = "package/Lychee/Bootstrap.lua"
    host = (root / host_path).read_text(encoding="utf-8")
    host = replace_one(host, r"^I\.VERSION = \{ api = \d+, revision = \d+ \}$",
                       f"I.VERSION = {{ api = {version}, revision = {revision} }}", host_path)
    types_path = "lychee-sdk/ApiStubs.lua"
    types = (root / types_path).read_text(encoding="utf-8")
    types = replace_one(types, r"^-- Editor-only API \d+ / revision \d+ declarations\.",
                        f"-- Editor-only API {version} / revision {revision} declarations.", types_path)
    for field, value in (("API_VERSION", version), ("API_REVISION", revision)):
        types = replace_one(types, rf"^---@field {field} \d+$", f"---@field {field} {value}", types_path)
    helper_path = "lychee-sdk/LycheeAPI.lua"
    helper = (root / helper_path).read_text(encoding="utf-8")
    helper = replace_one(helper,
                         r"^local API = \{ API_VERSION=\d+, API_REVISION=\d+,(?: MIN_API_REVISION=\d+,)? ERROR_CODES=\{\} \}$",
                         f"local API = {{ API_VERSION={version}, API_REVISION={revision}, MIN_API_REVISION={floor}, ERROR_CODES={{}} }}",
                         helper_path)
    code_lines = []
    for start in range(0, len(contract["errorCodes"]), 4):
        code_lines.append("    " + ", ".join(json.dumps(code) for code in contract["errorCodes"][start:start + 4]))
    helper = replace_one(helper, r"for _, code in ipairs\(\{.*?\}\) do",
                         "for _, code in ipairs({\n" + ",\n".join(code_lines) + "\n}) do", helper_path)
    helper = replace_one(helper, r"if minRevision==nil then minRevision=API\.[A-Z_]+ end",
                         "if minRevision==nil then minRevision=API.MIN_API_REVISION end", helper_path)
    manifest = ("# Generated by tools/build_sdk.py from tools/sdk_contract.json.\n"
                "name: lychee-sdk\nkind: development-package\nruntimeAddon: false\n"
                "hostAddon: Lychee\nfacade: _G.Lychee\n"
                f"apiVersion: {version}\napiRevision: {revision}\nhelperMinimumRevision: {floor}\ncontents:\n")
    manifest += "".join(f"  - {name}\n" for name in contract["contents"])
    return {host_path: host, types_path: types, helper_path: helper, "lychee-sdk/manifest.yaml": manifest}


def delivery_errors(root: Path, contract: dict) -> list[str]:
    sdk = root / "lychee-sdk"
    actual = {p.relative_to(sdk).as_posix() for p in sdk.rglob("*") if p.is_file()}
    declared = set(contract["contents"]) | {"manifest.yaml"}
    return ([f"required SDK file missing: {name}" for name in sorted(declared - actual)]
            + [f"SDK file absent from delivery contract: {name}" for name in sorted(actual - declared)])


def run(root: Path, write: bool = False) -> list[str]:
    """Return actionable violations; write only generated fields when explicitly requested."""
    contract = contract_at(root)
    errors = delivery_errors(root, contract)
    if errors:
        return errors
    generated = expected_files(root, contract)
    for name, expected in generated.items():
        path = root / name
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            if write:
                path.write_text(expected, encoding="utf-8", newline="\n")
            else:
                errors.append(f"SDK declaration drift: {name} (run python tools/build_sdk.py --write)")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="read-only consistency check (default)")
    mode.add_argument("--write", action="store_true", help="update generated declarations; no archive or publication")
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    args = parser.parse_args()
    try:
        errors = run(args.root.resolve(), write=args.write)
    except (OSError, ValueError, KeyError, TypeError) as error:
        errors = [str(error)]
    if errors:
        print("SDK contract FAILED", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print("SDK contract PASS: Host/types/helper current version, compatibility floor and complete delivery inventory")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
