"""Generate raid relations from a complete in-game Lychee Dev journal capture."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "docs/architecture/raid-journal"

def catalogue():
    raw=(DATA/"retail-zhCN.tsv").read_bytes()
    meta=json.loads((DATA/"manifest.json").read_text(encoding="utf-8"))
    assert meta["complete"] and not meta["outputTruncated"]
    assert hashlib.sha256(raw).hexdigest()==meta["sha256"]
    instances,bosses,difficulties={},{},{}
    header,end=None,None
    relations=0
    for line in raw.decode("utf-8").splitlines():
        fields=line.split("\t");kind=fields[0]
        if kind=="V": header=fields
        elif kind=="D": difficulties[int(fields[1])]=int(fields[2])
        elif kind=="I":
            id=int(fields[1]);assert id not in instances
            instances[id]=fields[2]
        elif kind=="B":
            id,owner,mask=int(fields[1]),int(fields[2]),int(fields[4]);assert id not in bosses and owner in instances
            assert 0<mask<=255
            bosses[id]={"id":id,"instance":owner,"name":fields[3],"mask":mask,"skills":{}}
        elif kind=="A":
            boss=bosses[int(fields[1])]
            for encoded in fields[2].split(";"):
                if not encoded:continue
                spell,section,mask=map(int,encoded.split(":"));assert spell>0 and section>0 and mask>0
                assert mask & boss["mask"] == mask
                choices=boss["skills"].setdefault(spell,{})
                for flag,diff in difficulties.items():
                    if mask & flag: choices[diff]=min(section,choices.get(diff,section))
                relations+=1
        elif kind=="END":end=list(map(int,fields[1:]))
        else:raise AssertionError("Unknown capture record: "+kind)
    assert header and header[1]=="lychee.raid-journal.v1" and header[3]==meta["environment"]["build"]
    assert end==[len(instances),len(bosses),relations]
    assert difficulties=={1:3,2:4,4:5,8:6,16:9,32:14,64:15,128:16}
    assert len(instances)<=256 and len(bosses)<=1024 and relations<=32768
    assert sum(len(b["skills"]) for b in bosses.values())<16384
    return meta,instances,bosses,difficulties

def render():
    meta,instances,bosses,difficulties=catalogue()
    quote=lambda s:json.dumps(s,ensure_ascii=False)
    lines=["-- Generated by tools/build_journal_catalog.py from an in-game journal capture.","-- No DB2 difficulty inference; descriptions and runtime name caches are not shipped.","local I = _G.LycheeInternal","I.Builtin.JournalCatalog = {",f'    build={quote(meta["environment"]["version"]+"."+meta["environment"]["build"])},',"    instances={"]
    for id in sorted(instances):lines.append(f'        [{id}]={{{quote(instances[id])}, "Interface\\\\AddOns\\\\Lychee\\\\Media\\\\MenuIcons\\\\skull.tga"}},')
    lines += ["    },",f"    encounterCount={len(bosses)},","    encounters={"]
    for b in bosses.values():lines.append(f'        {b["id"]}, {b["instance"]}, {quote(b["name"])},')
    lines += ["    },","    difficulties={"]
    for b in bosses.values():
        ds=",".join(str(d) for flag,d in difficulties.items() if flag & b["mask"])
        lines.append(f'        [{b["id"]}]={quote(ds)},')
    lines += ["    },","    -- Per encounter: spellID:sectionID:mask; mask bits map to 3,4,5,6,9,14,15,16.","    abilities={"]
    for b in bosses.values():
        parts=[]
        for spell,ds in sorted(b["skills"].items()):
            masks={}
            for flag,d in difficulties.items():
                if d in ds:masks[ds[d]]=masks.get(ds[d],0)+flag
            parts.extend(f"{spell}:{section}:{mask}" for section,mask in sorted(masks.items()))
        text=";".join(parts)
        if text:lines.append(f'        [{b["id"]}]={quote(text)},')
    lines += ["    },","}",""]
    return "\n".join(lines),len(bosses),sum(len(b["skills"]) for b in bosses.values())

if __name__=="__main__":
    parser=argparse.ArgumentParser();parser.add_argument("--check",action="store_true")
    rendered,bosses,skills=render();output=ROOT/"addon/Lychee/Builtin/Bosses/JournalCatalog.lua"
    if parser.parse_args().check:
        if output.read_text(encoding="utf-8")!=rendered:raise SystemExit("Journal catalogue generation drift")
    else:output.write_text(rendered,encoding="utf-8",newline="\n")
    print(f"Raid journal: {bosses} bosses, {skills} encounter/spell groups")
